version: '3.8'

services:
  product-analyzer:
    build: .
    ports:
      - "50071:50071"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50071/"]
      interval: 30s
      timeout: 10s
      retries: 3
