# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_analyzer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16product_analyzer.proto\x12\x0fproductanalyzer\"E\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\"$\n\x0fImageUrlRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\"H\n\rImageResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0bsearch_info\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\"6\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\x99\x02\n\x0fProductAnalyzer\x12R\n\x11GenerateFromImage\x12\x1d.productanalyzer.ImageRequest\x1a\x1e.productanalyzer.ImageResponse\x12X\n\x14GenerateFromImageUrl\x12 .productanalyzer.ImageUrlRequest\x1a\x1e.productanalyzer.ImageResponse\x12X\n\x0bHealthCheck\x12#.productanalyzer.HealthCheckRequest\x1a$.productanalyzer.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_analyzer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=43
  _globals['_IMAGEREQUEST']._serialized_end=112
  _globals['_IMAGEURLREQUEST']._serialized_start=114
  _globals['_IMAGEURLREQUEST']._serialized_end=150
  _globals['_IMAGERESPONSE']._serialized_start=152
  _globals['_IMAGERESPONSE']._serialized_end=224
  _globals['_HEALTHCHECKREQUEST']._serialized_start=226
  _globals['_HEALTHCHECKREQUEST']._serialized_end=246
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=248
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=302
  _globals['_PRODUCTANALYZER']._serialized_start=305
  _globals['_PRODUCTANALYZER']._serialized_end=586
# @@protoc_insertion_point(module_scope)
