# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import product_analyzer_pb2 as product__analyzer__pb2


class ProductAnalyzerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateFromImage = channel.unary_unary(
                '/productanalyzer.ProductAnalyzer/GenerateFromImage',
                request_serializer=product__analyzer__pb2.ImageRequest.SerializeToString,
                response_deserializer=product__analyzer__pb2.ImageResponse.FromString,
                )
        self.GenerateFromImageUrl = channel.unary_unary(
                '/productanalyzer.ProductAnalyzer/GenerateFromImageUrl',
                request_serializer=product__analyzer__pb2.ImageUrlRequest.SerializeToString,
                response_deserializer=product__analyzer__pb2.ImageResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/productanalyzer.ProductAnalyzer/HealthCheck',
                request_serializer=product__analyzer__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=product__analyzer__pb2.HealthCheckResponse.FromString,
                )


class ProductAnalyzerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateFromImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFromImageUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductAnalyzerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateFromImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFromImage,
                    request_deserializer=product__analyzer__pb2.ImageRequest.FromString,
                    response_serializer=product__analyzer__pb2.ImageResponse.SerializeToString,
            ),
            'GenerateFromImageUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFromImageUrl,
                    request_deserializer=product__analyzer__pb2.ImageUrlRequest.FromString,
                    response_serializer=product__analyzer__pb2.ImageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=product__analyzer__pb2.HealthCheckRequest.FromString,
                    response_serializer=product__analyzer__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productanalyzer.ProductAnalyzer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductAnalyzer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateFromImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productanalyzer.ProductAnalyzer/GenerateFromImage',
            product__analyzer__pb2.ImageRequest.SerializeToString,
            product__analyzer__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateFromImageUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productanalyzer.ProductAnalyzer/GenerateFromImageUrl',
            product__analyzer__pb2.ImageUrlRequest.SerializeToString,
            product__analyzer__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/productanalyzer.ProductAnalyzer/HealthCheck',
            product__analyzer__pb2.HealthCheckRequest.SerializeToString,
            product__analyzer__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
